### ISSUE TITLE
성능 개선

### ISSUE THREAD

**Issue by easyxxu** [easyxxu/Hodu-Market#99]
## 💡 성능 개선
라이트하우스 점수 측정을 통해 성능 개선 진행
### 📝 TODO
- [ ] 배너 이미지 최적화 (LCP)
- [ ] 이미지 width, height 추가 (CLS)
- [ ] 폰트 깜빡임 문제

### ETC
<img width="753" alt="스크린샷 2024-01-17 오후 3 23 54" src="https://github.com/easyxxu/Hodu-Market/assets/107910342/a3ca73ac-f6f6-4429-b288-f6f4ec15e097">

**Comment by easyxxu** [comment]
- 폰트 깜빡임 문제 : 0a8272bbc0c3a997dfbdea2cc011e7622f7a6bfc
- 이미지 width, height 추가 : 1c9ed0e14918ad2750e74751d438885e4687aadb
